image:
  repository: tccr.io/truecharts/alist
  pullPolicy: IfNotPresent
  tag: 3.2.1@sha256:ea5f9af09f474543e938672b637534bca5465a47aedb9c906f9d7143f8d15be0

service:
  main:
    ports:
      main:
        targetPort: 5244
        port: 10167

persistence:
  data:
    enabled: true
    mountPath: "/opt/alist/data"

portal:
  enabled: true
